### ISSUE TITLE
Time for 1.0.0?

### ISSUE THREAD

**Issue by jwalton** [mhart/StringStream#10]
I noticed you just pushed a 0.0.6 (I assume in response to https://nodesecurity.io/advisories/664?), but, a semver dependency on `^0.0.5` will not automatically pick up 0.0.6.  So to get your bugfix, I'm going to have to wait for the libraries I use which depend on stringstream to be updated.

It's been almost 6 years.  I think it's safe to declare 1.0.0.  ;)

**Comment by mhart** [comment]
Done! Rewrote (now only Node.js 4.x+ compatible)
