### ISSUE TITLE
Out-of-bounds Read vulnerability

### ISSUE THREAD

**Issue by ra100** [mhart/StringStream#12]
https://github.com/mhart/StringStream/blob/1efe3bf507bf3a1161f8473908b60e881d41422b/stringstream.js#L32

https://nodesecurity.io/advisories/664

**Comment by mhart** [comment]
This has already been fixed, see #7

**Comment by ra100** [comment]
Sorry, I've been confused by that I didn't see nsp updated with that vulnerability has been fixed. Maybe I've forgotten to hit F5 :)
