### ISSUE TITLE
Is pipe from stringstream work correctly?

### ISSUE THREAD

**Issue by mmmm1998** [mhart/StringStream#6]
Well, I have large gzip archive of kern.log `kern.log.2.gz` (72 megabytes).
Code for this file.
```JavaScript
const fs = require("fs")
const zlib = require('zlib')
const sstream = require("stringstream")

fs.createReadStream('kern.log.2.gz')
    .pipe(zlib.createGunzip())
    .pipe(sstream('utf8')) // stringstream
    .pipe(fs.createWriteStream('kern.log.2.sstream'))

fs.createReadStream('kern.log.2.gz')
    .pipe(zlib.createGunzip())
    .pipe(fs.createWriteStream('kern.log.2.try'))
```
After run I get: `kern.log.2.sstream` (480 kilobytes) and `kern.log.2.try` (1,4 gigabytes).
kern.log.2.sstream didn't ended correctly: the file contain only part of `kern.log.2.gz` information.
Is it conceived behavior?

**Comment by mhart** [comment]
Can you please retry with v1.0.0?

**Comment by mmmm1998** [comment]
Now all works fine: the result files are identical.
